apiVersion: v1
kind: Service
metadata:
  name: gke-vendor-order-service-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: gke-vendor-order-service
